#!/usr/bin/env python3

import os
import subprocess
import sys

def HasImage(name):
    return subprocess.call(
        ['docker', 'image', 'inspect', name],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL) == 0

def EnsureImage(root, name, file):
    if HasImage(name):
        return True
    return subprocess.call(
        ['docker', 'build', '-t', name, '-f', file, '.'],
        cwd=root) == 0

def main():
    root = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..'))
    if not EnsureImage(
        root,
        'adventofcode',
        os.path.join(root, 'etc/Dockerfile')):
        return 1
    return subprocess.call([
        'docker',
        'run',
        '-ti',
        '--rm',
        '-v', '{}:/src'.format(root),
        'adventofcode',
        '/bin/bash'
    ])

if __name__ == '__main__':
    sys.exit(main())